version: "3.8"
services:
  frontend:
    image: vicho314/kartingrm-frontend:latest
    depends_on:
      - backend
    networks:
      - front
    ports:
      - "8070-8072:80"
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 3

  database:
    image: postgres:alpine
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=vicho314
      - POSTGRES_DB=tingeso
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - back
    ports:
      - 5432:5432

  backend:
    image: vicho314/kartingrm-backend:latest
    networks:
      - back
      - front
    ports:
      - "8090-8092:8090"
    depends_on:
      - database
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=tingeso
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/tingeso
      - SPRING_DATASOURCE_USERNAME=vicho314
      - SPRING_DATASOURCE_PASSWORD=example
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 3

networks:
  back:
    driver: bridge
  front:
    driver: bridge

volumes:
  pgdata:
