version: "3.8"
services:
  frontend:
    image: 'vicho314/kartingrm-frontend:latest'
    networks:
      - front
    ports:
      - "8070:80"
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 3

  database:
    image: 'postgresql:alpine'
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=vicho314
      - POSTGRES_DB=tingeso
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - back
    ports:
      - 5432:5432

  backend:
    image: 'vicho314/kartingrm-backend:latest'
    networks:
      - back
      - front
    ports:
      - "8090:8090"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=tingeso
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tingeso
      - SPRING_DATASOURCE_USERNAME=vicho314
      - SPRING_DATASOURCE_PASSWORD=example
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 3

networks:
  back:
    driver: bridge
  front:
    driver: bridge
